name: 'Github CI — Deploy to GAE'
env:
    IMAGE_NAME: 'Shop-Town-server'
on:
    pull_request:
        branches:
            - main
        types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        name: Deploying to Google App Engine
        runs-on: ubuntu-latest

        if: github.event.pull_request.merged == true
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy to App Engine
              id: deploy
              uses: google-github-actions/deploy-appengine@v0.2.0
              with:
                  deliverables: app.yaml
                  project_id: ${{ secrets.GCP_PROJECT }}
                  credentials: ${{ secrets.GCP_CREDENTIALS }}
